# Generated by Django 4.1.5 on 2024-01-16 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buscador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut_empresa', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)])),
                ('Nombre_empresa', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(120)])),
                ('Rubro', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(120)])),
                ('Producto', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(120)])),
                ('Servicio', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(120)])),
                ('Descripcion', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(120)])),
                ('Pais', models.CharField(blank=True, choices=[('Chile', 'CHILE'), ('EEUU', 'USA'), ('China', 'CHINA')], max_length=120, null=True)),
                ('Estado', models.CharField(blank=True, choices=[], max_length=120, null=True)),
                ('Ciudad', models.CharField(blank=True, choices=[('Santiago', 'SANTIAGO'), ('Viña del Mar', 'VIÑA DEL MAR')], max_length=120, null=True)),
                ('Comuna', models.CharField(blank=True, choices=[], max_length=120, null=True)),
            ],
        ),
    ]
