# Generated by Django 5.0.1 on 2024-01-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empresa', models.CharField(db_column='RUT_EMPRESA', max_length=30)),
                ('nombre_empresa', models.CharField(db_column='NOMBRE_EMPRESA', max_length=500)),
                ('direccion_empresa', models.CharField(db_column='DIRECCION_EMPRESA', max_length=1000)),
                ('giro_empresa', models.CharField(db_column='GIRO_EMPRESA', max_length=1000)),
                ('logo_empresa', models.ImageField(blank=True, db_column='LOGO_EMPRESA', max_length=254, null=True, upload_to='images')),
                ('producto_servicio_empresa', models.CharField(db_column='PRODUCTO_SERVICIO_EMPRESA', max_length=254)),
                ('contacto_empresa', models.CharField(db_column='CONTACTO_EMPRESA', max_length=100)),
                ('email_empresa', models.EmailField(db_column='EMAIL_EMPRESA', max_length=100)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.AlterField(
            model_name='buscador',
            name='Comuna',
            field=models.CharField(blank=True, choices='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='buscador',
            name='Estado',
            field=models.CharField(blank=True, choices='', max_length=120, null=True),
        ),
    ]
