# Generated by Django 5.0.1 on 2024-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0002_empresa_alter_buscador_comuna_alter_buscador_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buscador',
        ),
        migrations.AddField(
            model_name='empresa',
            name='calificacion_empresa',
            field=models.ImageField(blank=True, db_column='CALIFICACION_EMPRESA', max_length=254, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificacion_empresa',
            field=models.CharField(blank=True, db_column='CERTIFICACION_EMPRESA', max_length=100, null=True),
        ),
    ]
