# Generated by Django 5.0.1 on 2024-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0003_delete_buscador_empresa_calificacion_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='certificacion_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_contacto',
            field=models.EmailField(blank=True, db_column='EMAIL_CONTACTO', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='validacion_empresa',
            field=models.CharField(blank=True, db_column='VALIDACION_EMPRESA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contacto_empresa',
            field=models.CharField(blank=True, db_column='CONTACTO_EMPRESA', max_length=100, null=True),
        ),
    ]
