# Generated by Django 5.0.1 on 2024-02-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0004_remove_empresa_certificacion_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_column='Empresa', max_length=500)),
                ('rubro', models.CharField(db_column='Rubro', max_length=500)),
                ('actividad', models.CharField(db_column='Actividad', max_length=500)),
                ('direccion', models.CharField(db_column='Direccion', max_length=3000)),
                ('region', models.CharField(db_column='Region', max_length=100)),
                ('comuna', models.CharField(db_column='Comuna', max_length=100)),
                ('estado', models.CharField(db_column='Estado', max_length=100)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=1000)),
                ('pais', models.CharField(db_column='Pais', max_length=100)),
                ('contacto', models.CharField(db_column='Contacto', max_length=500)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('validacion', models.CharField(db_column='Validacion', max_length=100)),
                ('calificacion', models.CharField(db_column='Calificacion', max_length=5000)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
    ]
