# Generated by Django 5.0.1 on 2024-02-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0005_empresas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='actividad',
            field=models.CharField(blank=True, db_column='Actividad', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='calificacion',
            field=models.CharField(blank=True, db_column='Calificacion', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ciudad',
            field=models.CharField(blank=True, db_column='Ciudad', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='comuna',
            field=models.CharField(blank=True, db_column='Comuna', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='contacto',
            field=models.CharField(blank=True, db_column='Contacto', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='direccion',
            field=models.CharField(blank=True, db_column='Direccion', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empresa',
            field=models.CharField(blank=True, db_column='Empresa', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='estado',
            field=models.CharField(blank=True, db_column='Estado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='pais',
            field=models.CharField(blank=True, db_column='Pais', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='region',
            field=models.CharField(blank=True, db_column='Region', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='rubro',
            field=models.CharField(blank=True, db_column='Rubro', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='validacion',
            field=models.CharField(blank=True, db_column='Validacion', max_length=100, null=True),
        ),
    ]
