# Generated by Django 5.0.1 on 2024-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0006_delete_empresa_alter_empresas_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='descripcion',
            field=models.CharField(blank=True, db_column='Descripcion', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='m_prima',
            field=models.CharField(blank=True, db_column='Materia_prima', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='precio',
            field=models.DecimalField(blank=True, db_column='Precio', decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='producto',
            field=models.CharField(blank=True, db_column='Producto', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='servicio',
            field=models.CharField(blank=True, db_column='Servicio', max_length=1000, null=True),
        ),
    ]
