# Generated by Django 5.0.1 on 2024-04-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0007_empresas_descripcion_empresas_m_prima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='m_prima',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='servicio',
        ),
    ]
