# Generated by Django 5.0.1 on 2024-02-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('username', models.CharField(db_column='username', max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('cod_emp', models.IntegerField(db_column='COD_EMP')),
                ('rut_empresa', models.IntegerField(db_column='RUT_EMPRESA')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
