# Generated by Django 5.0.1 on 2024-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreciosPromedios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('promedio', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField()),
            ],
        ),
    ]
