# Generated by Django 5.0.1 on 2024-04-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Economicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoZapatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('promedio', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField()),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
    ]
