from django import forms

ESTADOS= [
    ('AL','Alabama'),
    ('AK','Alaska'),
    ('AR','Arisona'),
    ('AA','Arkansas'),
    ('CA','California'),
    ('CN','Carolina del Norte'),
    ('CS','Carolina del Sur'),
    ('CO','Colorado'),
    ('CT','Connecticut'),
    ('DN','Dakota del Norte'),
    ('DS','Dakota del Sur'),
    ('DE','Delaware'),
    ('FL','Florida'),
    ('GE','Georgia'),
    ('HA','Hawái'),
    ('ID','Idaho'),
    ('IL','Illinois'),
    ('IN','Indiana'),
    ('IO','Iowa'),
    ('KA','Kansas'),
    ('KE','Kentucky'),
    ('LU','Luisiana'),
    ('MA','Maine'),
    ('ME','Meryland'),
    ('MS','Massachusetts'),
    ('MI','Michigan'),
    ('MN','Minnesota'),
    ('MP','Misisipi'),
    ('MU','Misuri'),
    ('MO','Montana'),
    ('NK','Nebraska'),
    ('NE','Nevada'),
    ('NJ','Nueva Jersey'),
    ('NY','Nueva York'),
    ('NH','Nuevo Hampshire'),
    ('NM','Nuevo México'),
    ('OH','Ohio'),
    ('OK','Oklahoma'),
    ('OR','Oregon'),
    ('PE','Pensilvania'),
    ('RH','Rhode Island'),
    ('TE','Tennessee'),
    ('TX','Texas'),
    ('UT','Utah'),
    ('VE','Vermont'),
    ('VI','Virginia'),
    ('WV','West Virginia'),
    ('WA','Washington'),
    ('WI','Wisconsin'),
    ('WY','Wyoming'),
]
REGIONES = [
    ('1','Arica y Parinacota'),
    ('2','Tarapacá'),
    ('3','Antofagasta'),
    ('4','Atacama'),
    ('5','Coquimbo'),
    ('6','Valparaíso'),
    ('7',"O'Higgins"),
    ('8','Maule'),
    ('9','Ñuble'),
    ('10','Bio-Bío'),
    ('11','La Araucanía'),
    ('12','Los Ríos'),
    ('13','Los Lagos'),
    ('14','Aysén'),
    ('15','Magallanes'),
    ('16','Metropilitana'),
]

class DatosForms(forms.Form):
    
    estados = forms.ChoiceField(max_length=20,choices=ESTADOS)
    regiones = forms.FileField(max_length=20, choices=REGIONES)